In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data


# Defining inputs and collecting them from Mnist

In [2]:
mnist = input_data.read_data_sets("tmp/data/",one_hot=True)

print(np.shape(x_raw))
print(y_raw)

Extracting tmp/data/train-images-idx3-ubyte.gz
Extracting tmp/data/train-labels-idx1-ubyte.gz
Extracting tmp/data/t10k-images-idx3-ubyte.gz
Extracting tmp/data/t10k-labels-idx1-ubyte.gz
(50, 784)
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0

In [11]:
n_input = 28*28 #image_width*image_height
n_hidden = 2
n_classes = 10


tf.reset_default_graph()


# Defining weights and biases 

In [16]:
W = { "h1": tf.Variable(tf.ones([3,3,1,32])),
        "h2": tf.Variable(tf.ones([3,3,32,64])),
        "h3": tf.Variable(tf.ones([12*12*64,128])),
        "out": tf.Variable(tf.ones([128,n_classes])),
}

b = { "b1": tf.Variable(tf.zeros([32])),
        "b2": tf.Variable(tf.zeros([64])),
        "b3": tf.Variable(tf.zeros([128])),
        "bout": tf.Variable(tf.zeros([n_classes])),
}
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])



In [17]:
#reshaping inputs

In [18]:
xi = tf.reshape(x,[-1,28,28,1])

# Biulding model

In [19]:
l1 = tf.nn.conv2d(xi,W["h1"],strides=[1,1,1,1],padding="VALID")
l1_b = tf.nn.bias_add(l1,b["b1"])
l1_act = tf.nn.relu(l1_b)

l2 = tf.nn.conv2d(l1_act,W["h2"],strides=[1,1,1,1],padding="VALID")
l2_b = tf.nn.bias_add(l2,b["b2"])
l2_act = tf.nn.relu(l2_b)

l3_max = tf.nn.max_pool(l2_act,[1,2,2,1],strides=[1,2,2,1],padding="VALID")

# Dense
l4 = tf.reshape(l3_max,[-1,12*12*64])
l4 = tf.matmul(l4,W["h3"])
l4_b = tf.nn.bias_add(l4,b["b3"])
l4_act = tf.nn.relu(l4_b)

l5 = tf.matmul(l4,W["out"])+b["bout"]
out_act = tf.nn.softmax(l5)


In [20]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=l5,labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

# Training model

In [54]:
with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        x_raw,y_raw = mnist.train.next_batch(20)
        #pred = l1_b.eval({x: x_raw})
        #print(pred)
        for i in range(10000):
              if(i%100==0):
                    print(i)
              kk = sess.run(optimizer,feed_dict={x: x_raw,y: y_raw})
        pred = out_act.eval({x: x_raw})
        
      

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900


# Results 

In [56]:
np.shape(pred)

(20, 10)

In [59]:
for i in range(20):
    print("pred is :{} , actual value is: {}".format(np.argmax(pred[i]),np.argmax(y_raw[i])))
#bc of initializing ones it's take so many time to train good


pred is :2 , actual value is: 2
pred is :7 , actual value is: 7
pred is :0 , actual value is: 8
pred is :2 , actual value is: 0
pred is :2 , actual value is: 1
pred is :0 , actual value is: 0
pred is :2 , actual value is: 2
pred is :0 , actual value is: 8
pred is :2 , actual value is: 0
pred is :2 , actual value is: 2
pred is :7 , actual value is: 7
pred is :7 , actual value is: 3
pred is :7 , actual value is: 7
pred is :7 , actual value is: 5
pred is :7 , actual value is: 5
pred is :2 , actual value is: 1
pred is :2 , actual value is: 8
pred is :7 , actual value is: 2
pred is :2 , actual value is: 2
pred is :7 , actual value is: 6


# for evaluating some weights or etc just use:

In [ ]:
#evaluating weights of first hidden layer:
m = W["h1"].eval()